config/routes.rb
Curio::Application.routes.draw do
  mount S3Multipart::Engine => "/s3_multipart"

  devise_for :users, controllers: { registrations: "registrations", confirmations: "confirmations",
                                    sessions: "sessions" }

  devise_scope :user do
    match '/user/confirmation' => 'confirmations#update', via: :put, as: :update_user_confirmation
  end

  get 'thankyou' => 'landing_page#thankyou'

  resources :enrolments, only: :index do
    post :progress, on: :member
  end

  resources :authored_courses, only: :index
  resources :gaming_events, only: [:create, :update, :destroy] do
    post :discover, on: :member
  end

  resources :courses do
    resources :course_chapters do
      get :gamify, on: :member
    end

    member do
      post :reorder
      post :enrol
      get :watch
    end

    collection do
      get :search
      post :search
    end
  end

  resources :course_chapters, only: :create # stub

  resources :users, only: [:index, :show] do
    put :avatar, on: :collection
    resources :score_activities, only: :index
  end

  resources :tutors, only: [:index, :show]
  resources :essays

  namespace :admin do
    root to: "users#index"

    resources :courses, only: [:index, :edit, :destroy]

    resources :users do
      put :approve, on: :member
    end
  end

  get 'tags' => 'tags#index', as: 'tags'

  authenticated :user, ->(u) { u.has_role?(:creative) } do
    root to: "authored_courses#index", as: :tutor_root
  end

  authenticated :user, ->(u) { u.has_role?(:student) } do
    root to: "enrolments#index", as: :student_root
  end

  root to: "landing_page#index"

end

app/views/layouts/admin/application.html.erb
<% content_for :admin_nav do %>
  <div class="row">
    <div class="container">
      <ul class="nav nav-pills">
        <li class="<%= "active" if params[:controller] == "admin/users" %>">
          <%= link_to t("activerecord.models.user").pluralize, admin_users_path %>
        </li>

        <li class="<%= "active" if params[:controller] == "admin/courses" %>">
          <%= link_to t("activerecord.models.course").pluralize, admin_courses_path %>
        </li>
      </ul>
    </div>
  </div>
  <div class="top-2"></div>
<% end %>

<%= render template: "layouts/application" %>