config/routes.rb
Curio::Application.routes.draw do
  mount S3Multipart::Engine => "/s3_multipart"

  devise_for :users, controllers: { registrations: "registrations", confirmations: "confirmations",
                                    sessions: "sessions" }

  devise_scope :user do
    match '/user/confirmation' => 'confirmations#update', via: :put, as: :update_user_confirmation
  end

  get 'thankyou' => 'landing_page#thankyou'

  resources :enrolments, only: :index do
    post :progress, on: :member
  end

  resources :authored_courses, only: :index
  resources :gaming_events, only: [:create, :update, :destroy] do
    post :discover, on: :member
  end

  resources :courses do
    resources :course_chapters do
      get :gamify, on: :member
    end

    member do
      post :reorder
      post :enrol
      get :watch
    end

    collection do
      get :search
      post :search
    end
  end

  resources :course_chapters, only: :create # stub

  resources :users, only: [:index, :show] do
    put :avatar, on: :collection
    resources :score_activities, only: :index
  end

  resources :tutors, only: [:index, :show]
  resources :essays

  namespace :admin do
    root to: "users#index"

    resources :courses, only: [:index, :edit, :destroy]

    resources :users do
      put :approve, on: :member
    end
  end

  get 'tags' => 'tags#index', as: 'tags'

  authenticated :user, ->(u) { u.has_role?(:creative) } do
    root to: "authored_courses#index", as: :tutor_root
  end

  authenticated :user, ->(u) { u.has_role?(:student) } do
    root to: "enrolments#index", as: :student_root
  end

  root to: "landing_page#index"

end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < Admin::ApplicationController
  inherit_resources
  respond_to :html, :js

  def edit
    js "Courses#new", course: resource.as_json(include: :course_chapters)
    render template: "courses/edit"
  end

  def collection
    @search = end_of_association_chain.includes(:author)
      .order("#{sort_attr} #{sort_direction}").search(params[:q])
    @courses = @search.result.page(params[:page])
  end

  private

  def sort_attr
    if params[:sort_attr] == "author"
      "users.name || users.email"
    else
      super || "title"
    end
  end
end

app/controllers/courses_controller.rb
# encoding: utf-8

class CoursesController < InheritedResources::Base
  include ActionView::RecordIdentifier

  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :save_after_update_path, only: :edit
  after_filter :update_pageviews, only: :show

  load_and_authorize_resource
  skip_load_and_authorize_resource only: :watch
  respond_to :html, :js, :json

  def search
    js :index

    index! do |format|
      format.html { render :index }
    end
  end

  def new
    js course: @course.as_json(include: [:author, :course_chapters])
    new!
  end

  def edit
    js :new, course: @course.as_json(include: [:author, :course_chapters])
    edit!
  end

  def create
    js :new
    @course = Course.new(build_resource_params.first)
    set_upload_data

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_course_chapters_path(@course) }
        format.json { render status: 200, json: @course }
      else
        flash[:error] = @course.errors.full_messages.join(", ")
        format.html { render :new }
        format.json { render status: 422, json: @course.errors }
      end
    end
  end

  def update
    js :new
    @course = Course.find(params[:id])
    set_upload_data

    respond_to do |format|
      if @course.update_attributes(build_resource_params.first)
        format.html { session.delete(:return_to) || @course }
        format.json { render status: 200, json: @course }
      else
        format.html { render :edit }
        format.json { render status: 422, json: @course.errors }
      end
    end
  end

  def build_resource_params
    [params.fetch(:course, {}).permit(:author_id, :title, :intro, :description, :fee)]
  end

  def collection
    @search = end_of_association_chain.viewable.search(params[:q])
    @courses = @search.result.page(params[:page]).per(12)
  end

  def reorder
    respond_to do |format|
      status, msg = resource.reorder(params[:order])

      if status
        format.js { render status: 200, nothing: true }
      else
        flash[:error] = t("controllers.courses.reorder.error")
        format.js { render status: 500, text: msg }
      end
    end
  end

  def enrol
    @course = Course.find(params[:id])

    respond_to do |format|
      if current_user.accepted_courses << @course
        add_score(@course)
        add_score(@course.enrolments.where(user_id: current_user.id).last, owner: @course.author, action: "create")
        flash[:notice] = t("controllers.courses.enrol.success")
        format.html { redirect_to watch_course_path(@course) }
        format.js
      else
        flash[:error] = t("controllers.courses.enrol.error")
        format.html { redirect_to :back }
        format.js { render status: 500, text: flash[:error] }
      end
    end
  end

  def watch
    @course = Course.find(params[:id])
    @enrolment = @course.enrolments.where(user_id: current_user.id).first
    @current_chapter = params[:c] ? CourseChapter.find(params[:c]) : @enrolment.current_chapter
    authorize! :watch, @current_chapter
    js enrolment: @enrolment.slice("id", "completed_at"),
       discovered: @current_chapter.gaming_events.discovered(@enrolment),
       undiscovered: @current_chapter.gaming_events.undiscovered(@enrolment),
       target: dom_id(@current_chapter)
  end

  private

  def set_upload_data
    if key = params[:course_key]
      @course.intro.key = key
      @course.s3_multipart_upload = S3Multipart::Upload.find_by(key: key)
    end
  end

  def update_pageviews
    if user_signed_in?
      resource.user_views << current_user.id
    else
      resource.anonymous_views << IPAddr.new(request.remote_ip).hton
    end
  end
end

app/views/courses/_course.html.erb
<li id="<%= dom_id(course) %>" class="<%= dom_id(course) %> clearfix">
  <div class="pull-left">
    <div>
      <%= link_to image_tag(course.intro.thumb_small), can?(:watch, course) ? watch_course_path(course) : course %>
    </div>
    <% if can? :enrol, course %>
      <%= link_to t("course.enrol", count: course.fee), enrol_course_path(course),
                  class: "btn btn-lg btn-success btn-block", method: :post %>
    <% end %>
  </div>

  <div>
    <h4><%= link_to course, can?(:watch, course) ? watch_course_path(course) : course %></h4>

    <% if current_user != course.author %>
      <p>
        <%= t(".chapter_count", count: course.course_chapters.count) %>
        <%= link_to course.author, tutor_path(course.author) %>
      </p>
    <% end %>

    <% if course.description.present? %>
      <p class="text-muted"><%= truncate(course.description, length: 128) %></p>
    <% end %>
  </div>

  <span class="action-links">
    <% if can? :update, course %>
      <%= link_to edit_course_path(course) do %>
        <%= fa_icon "edit" %>
      <% end %>
    <% end %>

    <% if can? :destroy, course %>
      <%= link_to course, method: :delete,
                          remote: true, data: { confirm: t("confirm_delete", scope: "course") } do %>
        <%= fa_icon "times" %>
      <% end %>
    <% end %>
  </span>
</li>

app/views/courses/_form.html.erb
<div id="upload-status" class="alert alert-info">
  <%= fa_icon "info-circle" %>&nbsp;<span></span>
</div>

<div class="row">
  <div id="direct-uploader" class="direct-uploader" data-fileupload-options='{"uploadTemplateId":"video-upload-tmpl"}'>
    <%= render "courses/main_form" %>
  </div>
</div>

<div class="top-2"></div>

<div class="row">
  <div id="sortable-chapters" class="panel-group">
    <div class="text-center">
      <p class="lead text-muted"><%= t(".hint.dropzone") %></p>
      <em class="text-muted"><%= t(".hint.edit_chapters").html_safe %></em>
      <%= button_tag t("save_order"), class: "btn btn-primary save-order" %>
    </div>

    <div id="chapter-container" class="sortable">
      <%= render partial: "course_chapters/form", collection: @course.course_chapters, as: :chapter %>
    </div>
  </div>
</div>

<div id="new-chapter-container">
  <%= render "course_chapters/form", chapter: @course.course_chapters.build %>
</div>

<%= render "shared/video_upload" %>
<script type="text/x-tmpl" id="template-download"></script>

app/views/courses/_general_info.html.erb
<p class="text-muted"><%= @course.description %></p>
<h4 class="text-center text-info"><%= t(".created_by") %></h4>

<div class="media inset">
  <%= link_to tutor_path(@course.author), class: "pull-left" do %>
    <%= image_tag @course.author.avatar.small, alt: @course.author %>
    <h4 class="text-center text-muted"><%= @course.author.score %></h4>
  <% end %>

  <div class="media-body">
    <p><%= @course.author %></p>
    <p class="text-muted"><%= @course.author.bio %></p>
  </div>
</div>

<div class="top-1"></div>

<table id="course-stats" class="table">
  <tbody>
    <% if @course.unique_views > 0 %>
      <tr>
        <td><%= @course.unique_views %></td>
        <td><%= t(".views", count: @course.unique_views) %></td>
      </tr>
    <% end %>

    <% if @course.enrolments.present? %>
      <tr>
        <td><%= @course.enrolments.count %></td>
        <td><%= t(".enrolments", count: @course.enrolments.count) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/_intro.html.erb
<div class="video-wrapper text-center">
  <%= render "shared/video", video: @course.intro %>
</div>

app/views/courses/_main_form.html.erb
<div class="col-lg-4 col-md-6 col-lg-offset-1 col-md-offset-1 uploader-form">
  <%= simple_form_for @course, html: { id: "course-upload", multipart: true, data: { model: "course" } } do |f| %>
    <div class="dropzone fade">
      <%= f.file_field :intro, class: ("validate[condRequired[if[dropzoneEmpty]],funcCall[validateDuration]]" unless @course.intro.present?),
                       data: { uploader: S3Multipart::Uploader.serialize("CourseUploader"),
                               "jqv-prompt-at" => "#direct-uploader .dropzone",
                               "errormessage-value-missing" => t("upload_missing") } %>
      <div class="image-preview">
        <% if @course.intro.present? %>
          <%= render "shared/video", video: @course.intro %>
        <% end %>
      </div>
      <%= t(".dropzone") %>
    </div>

    <%= f.button :button, t("save"), class: "btn-primary btn-lg btn-block main-submit save-all" %>

    <div class="btn-group btn-group-justified">
      <%= link_to("#", class: "btn btn-default upload-control resume") { fa_icon "upload" } %>
      <%= link_to("#", class: "btn btn-default upload-control pause") { fa_icon "pause" } %>
      <%= link_to("#", class: "btn btn-default upload-control cancel") { fa_icon "ban" } %>
    </div>
  <% end %>
</div>

<div class="right-column main-form">
  <%= simple_form_for @course, html: { class: "form-horizontal" },
                      wrapper: :bootstrap3_horizontal, defaults: { right_column_html: { class: "col-sm-10" },
                      label_html: { class: "col-sm-2 sr-only" } }, remote: true do |f| %>
    <legend class="text-center"><%= @course.new_record? ? t(".legend") : @course %></legend>

    <%= f.error_notification %>

    <% if current_user.has_role?(:admin) %>
      <%= f.association :author, as: :string, input_html: { class: "select2-field validate[required]" }, placeholder: t(".author") %>
    <% else %>
      <%= f.association :author, as: :hidden, input_html: { value: current_user.id } %>
    <% end %>

    <%= f.input :title, placeholder: t(".title"), input_html: { class: "validate[required] input-sm" } %>

    <% f.with_options input_html: { class: "input-sm" } do |ff| %>
      <%= ff.input :description, placeholder: t(".description") %>
      <%#= ff.input :level, collection: Course::LEVELS, include_blank: false,
                  right_column_html: { class: "col-lg-4 col-md-6 col-sm-8" } %>

      <%#= ff.association :topics %>
    <% end %>

    <div class="form-group">
      <%= f.label :fee, class: "col-lg-2 col-md-2 col-sm-2 sr-only" %>
      <div class="col-xs-10 col-sm-8 col-md-6 col-lg-4">
        <div class="input-group">
          <span class="input-group-addon">$</span>
          <%= f.input :fee, wrapper: false, label: false, right_column_html: false, placeholder: "00",
                      input_html: { class: "validate[custom[number],min[0]] input-sm",
                                    value: @course.fee.to_i } %>
          <span class="input-group-addon">.00</span>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/edit.html.erb
<%= render "courses/form" %>

app/views/courses/index.html.erb
<div id="course-list" data-overlay="true">
  <ul class="grid-list clearfix main-list">
    <%= render @courses %>
  </ul>

  <%= paginate @courses, remote: true %>
</div>

app/views/courses/new.html.erb
<%= render "form" %>

app/views/courses/show.html.erb
<div class="row">
  <% for_device_type :desktop, :tablet do %>
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-8">
        <h3 class="text-center text-info"><%= @course %></h3>

        <%= render "intro" %>

      </div>

      <div class="col-lg-4 col-md-4 col-sm-4">
        <%= render "general_info" %>

        <% if can? :enrol, @course %>
          <%= link_to t("course.enrol", count: @course.fee), enrol_course_path(@course),
                      class: "btn btn-lg btn-success btn-block", method: :post %>
        <% end %>

        <div class="btn-group btn-group-justified">
          <%= link_to t(".edit_content"), edit_course_path(@course), class: "btn btn-default" if can?(:update, @course) %>
          <%= link_to t("destroy"), @course, method: :delete, class: "btn btn-danger",
                          data: { confirm: t("confirm_delete", scope: "course") } if can?(:destroy, @course) %>
        </div>
      </div>
    </div>

    <div class="top-2"></div>

    <div class="row">
      <ul id="course-chapters" class="grid-list-3">
        <%= render @course.course_chapters %>
      </ul>
    </div>
  <% end %>

  <% for_device_type :mobile do %>
    <div class="container">
      <div class="col-lg-10">
        <h3 class="text-center text-info"><%= @course %></h3>

        <%= render "general_info" %>

        <div class="text-center">
          <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#course-intro">
            <%= t(".watch_intro") %>
          </button>
        </div>

        <ul id="course-chapters-mobile">
          <% @course.course_chapters.each do |chapter| %>
            <li>
              <%= render "course_chapters/general_info", course_chapter: chapter %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div id="course-intro" class="modal fade">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"><%= @course %></h4>
          </div>

          <div class="modal-body">
            <%= render "intro" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/watch.html.erb
<%= content_for :main_area do %>
  <h2 class="text-center text-info"><%= @course %></h2>

  <div id="current-chapter" class="row">
    <%= render "enrolments/current_chapter", chapter: @current_chapter %>
  </div>

  <div id="chapter-list" class="row">
    <ul class="grid-list-3 main-list">
      <% @course.course_chapters.each do |chapter| %>
        <% klass = if @current_chapter == chapter
            "current"
          elsif cannot?(:watch, chapter)
            "incomplete"
          end %>

        <li id="item-<%= dom_id(chapter) %>" class="<%= klass %>">
          <%= link_to watch_course_path(id: @course.id, c: chapter.id), remote: true do %>
            <% for_device_type :mobile, :tablet do %>
              <h5 class="text-center"><%= chapter %></h5>
              <p><small><%= truncate(chapter.description, length: 100) %></small></p>
            <% end %>

            <% for_device_type :desktop do %>
              <div>
                <%= image_tag(chapter.video.thumb_small, alt: chapter.title) %>
                <span class="chapter-caption">
                  <h5><%= chapter %></h5>
                  <p><small><%= truncate(chapter.description, length: 255) %></small></p>
                </span>
              </div>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= content_for :event_bucket do %>
  <p id="triggered-events-placeholder" class="text-center text-muted">
    <%= t(".triggered_events_placeholder") %>
  </p>
  <ul id="triggered-events"></ul>
<% end %>

<% for_device_type :desktop, :tablet do %>
  <div class="col-md-9">
    <%= yield :main_area %>
  </div>

  <div class="col-md-3">
    <%= yield :event_bucket %>
  </div>
<% end %>

<% for_device_type :mobile do %>
  <div class="row">
    <%= yield :main_area %>
  </div>

  <div class="row">
    <%= yield :event_bucket %>
  </div>
<% end %>