config/routes.rb
Curio::Application.routes.draw do
  mount S3Multipart::Engine => "/s3_multipart"

  devise_for :users, controllers: { registrations: "registrations", confirmations: "confirmations",
                                    sessions: "sessions" }

  devise_scope :user do
    match '/user/confirmation' => 'confirmations#update', via: :put, as: :update_user_confirmation
  end

  get 'thankyou' => 'landing_page#thankyou'

  resources :enrolments, only: :index do
    post :progress, on: :member
  end

  resources :authored_courses, only: :index
  resources :gaming_events, only: [:create, :update, :destroy] do
    post :discover, on: :member
  end

  resources :courses do
    resources :course_chapters do
      get :gamify, on: :member
    end

    member do
      post :reorder
      post :enrol
      get :watch
    end

    collection do
      get :search
      post :search
    end
  end

  resources :course_chapters, only: :create # stub

  resources :users, only: [:index, :show] do
    put :avatar, on: :collection
    resources :score_activities, only: :index
  end

  resources :tutors, only: [:index, :show]
  resources :essays

  namespace :admin do
    root to: "users#index"

    resources :courses, only: [:index, :edit, :destroy]

    resources :users do
      put :approve, on: :member
    end
  end

  get 'tags' => 'tags#index', as: 'tags'

  authenticated :user, ->(u) { u.has_role?(:creative) } do
    root to: "authored_courses#index", as: :tutor_root
  end

  authenticated :user, ->(u) { u.has_role?(:student) } do
    root to: "enrolments#index", as: :student_root
  end

  root to: "landing_page#index"

end

app/models/user.rb
require 'redis_extensions'

class User < ActiveRecord::Base
  include Redis::Objects
  include Redis::Extensions

  mount_uploader :avatar, AvatarUploader

  BIO_LIMIT   = 256
  NAME_LIMIT  = 48

  rolify
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :authored_courses, class_name: "Course", foreign_key: :author_id
  has_many :enrolments, dependent: :destroy
  has_many :accepted_courses, through: :enrolments, source: :course
  has_many :score_activities, class_name: "ScoreActivity", foreign_key: :owner_id, dependent: :destroy
  has_many :essays

  sorted_set :scoreboard, global: true

  with_options if: ->(u) { u.has_role?(:creative) }, on: :create do |u|
    u.validates_url :website
    u.validates :website, presence: true
  end

  validates :email, format: { with: /\A(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})\z/i }

  validates_integrity_of :avatar
  validates_processing_of :avatar

  with_options if: ->(u) { (u.approved? && !u.approved_changed? && u.confirmed?) && !u.has_role?(:admin) }, allow_blank: true do |u|
    u.validates :name, length: { in: 3..NAME_LIMIT }
    u.validates :bio, length: { in: 16..BIO_LIMIT }
  end

  before_create :approve_admin
  after_create :notify_admin, :add_user_to_mailchimp, :send_thanks
  after_create -> { confirm! if has_role?(:admin) }
  before_destroy :remove_user_from_mailchimp

  default_scope { order("score desc") }
  scope :lookup_by_email, ->(param) { where('users.email ilike ?', "%#{ param }%") if param }
  scope :lookup_by_email_or_name, ->(param) { where('users.email ilike ? or users.name ilike ?', "%#{ param }%", "%#{ param }%") if param }

  # prelaunch
  # override Devise method
  # no password is required when the account is created; validate password when the user sets one
  validates_confirmation_of :password
  def password_required?
    if !persisted?
      !(password != "")
    else
      !password.nil? || !password_confirmation.nil?
    end
  end

  def completed_courses
    accepted_courses.merge(enrolments.complete)
  end

  def incomplete_courses
    accepted_courses.merge(enrolments.incomplete)
  end

  # override Devise method
  def confirmation_required?
    false
  end

  # new function to determine whether a password has been set
  def has_no_password?
    self.encrypted_password.blank?
  end

  # new function to provide access to protected method pending_any_confirmation
  def only_if_unconfirmed
    pending_any_confirmation {yield}
  end

  def attempt_set_password(params)
    p = {}
    p[:password] = params[:password]
    p[:password_confirmation] = params[:password_confirmation]
    update_attributes(p)
  end
  # end prelaunch

  def active_for_authentication?
    super && approved? && (confirmed? || confirmation_period_valid?)
  end

  def inactive_message
    approved? ? super : :not_approved
  end

  def display_name
    self.name.blank? ? self.email : self.name
  end

  def to_s
    self.display_name
  end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif !recoverable.confirmed?
      recoverable.errors[:base] << I18n.t("devise.failure.unconfirmed")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end

  def self.valid_attribute?(attr, value)
    mock = self.new(attr => value)
    if mock.valid?
      true
    else
      !mock.errors.has_key?(attr)
    end
  end

  def notify_admin
    AdminMailer.new_user_notify(self.id).deliver
  end

  private

  def approve_admin
    self.approved = true if has_role?(:admin)
  end

  def send_thanks
    UserMailer.thanks(self.id).deliver
  end

  def add_user_to_mailchimp
    return if ENV['ADMIN_EMAIL'].blank? || ENV['MAILCHIMP_LIST_ID'].blank? || self.email.include?(ENV['ADMIN_EMAIL'])
    mailchimp = Gibbon::API.new
    result = mailchimp.lists.subscribe({
      id: ENV['MAILCHIMP_LIST_ID'],
      email: { email: self.email },
      double_optin: false,
      update_existing: true,
      send_welcome: false
      })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  rescue Gibbon::MailChimpError => e
    Rails.logger.info("MailChimp subscribe failed for #{self.email}: " + e.message)
  end

  def remove_user_from_mailchimp
    return if ENV['MAILCHIMP_LIST_ID'].blank?
    mailchimp = Gibbon::API.new
    result = mailchimp.lists.unsubscribe({
      id: ENV['MAILCHIMP_LIST_ID'],
      email: { email: self.email },
      delete_member: true,
      send_goodbye: false,
      send_notify: false
      })
    Rails.logger.info("Unsubscribed #{self.email} from MailChimp") if result
  rescue Gibbon::MailChimpError => e
    Rails.logger.info("MailChimp unsubscribe failed for #{self.email}: " + e.message)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  inherit_resources
  respond_to :html, :js

  def index
    index! do |success|
      @users = @users.order("#{sort_attr} #{sort_direction}").
          lookup_by_email(params[:search]).
          page(params[:page]).per(params[:per_page])
      @users = @users.where(approved: params[:pending] != "on") if params[:pending]
    end
  end

  def show
    show! do |success|
      success.html { render partial: "show", layout: !request.xhr? }
    end
  end

  def approve
    @user = User.find(params[:id])
    @user.update_attribute(:approved, true)
    @user.send_confirmation_instructions

    respond_to do |format|
      format.js { render template: "admin/users/update" }
    end
  end

  def build_resource_params
    [params.require(:user).permit(:email, :password, :password_confirmation,
                                  :name, :bio, :website, :approved)]
  end

  private

  def sort_attr
    super || "email"
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  before_filter :authenticate_user!
  load_and_authorize_resource except: :avatar
  actions :index
  respond_to :html, :json, :js

  def index
    @users = User.lookup_by_email_or_name(params[:q]).limit(5) if params[:q]
    index!
  end

  def avatar
    resource = current_user

    respond_to do |format|
      if User.valid_attribute?(:avatar, params[:user][:avatar])
        resource.update_attribute(:avatar, params[:user][:avatar])
        flash[:notice] = t("controllers.users.avatar.success")
        format.js
      else
        flash[:error] = t("controllers.users.avatar.error")
        format.js { render status: 500, text: t("controllers.users.avatar.error") }
      end
    end
  end
end

app/views/admin/users/_show.html.erb
<div class="<%= dom_id(@user) %>">
  <h5><%= @user.email %></h5>
  <p class="text-muted">
    <i><%= "#{t("activerecord.attributes.user.created_at")}: #{l(@user.created_at, format: "%e %b %Y at %I:%M %p")}" %></i>
  </p>
  <p>
    <span class="text-muted"><%= t("activerecord.attributes.user.roles") + ": " %></span>
    <%= @user.roles.map { |r| t("role.#{r.name}") }.join(", ") %>
  </p>

  <% if @user.website.present? %>
    <p>
      <span class="text-muted"><%= t("activerecord.attributes.user.website") + ": " %></span>
      <%= link_to @user.website, @user.website, target: "_blank" %>
    </p>
  <% end %>
</div>

app/views/admin/users/_user.html.erb
<tr id="<%= dom_id(user) %>" class="<%= "pending " unless user.approved? %> <%= dom_id(user) %>">
  <td class="email">
    <%= link_to user.email, "#user-details", class: "remote",
                data: { ajax_target: "#user-details", source: admin_user_path(user) } %>
  </td>

  <td> <%= l user.created_at, format: "%e %b %Y" %> </td>

  <td class="user-actions approve">
    <% if can?(:update, user) && !user.approved? %>
      <%= link_to approve_admin_user_path(user), method: :put, remote: true, title: t(".approve") do %>
        <%= fa_icon "thumbs-up" %>
      <% end %>
    <% end %>
  </td>

  <td class="user-actions destroy">
    <% if can? :destroy, user %>
      <%= link_to admin_user_path(user), class: "close", method: :delete,
                  remote: true, data: { confirm: t("confirm_delete", scope: "user") } do %>
        <%= fa_icon "times" %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/admin/users/_user_list.html.erb
<div id="users-list" data-overlay="true">
  <%= label_tag :pending, class: "checkbox" do %>
    <%= check_box_tag :pending, nil, params[:pending] %>
    <%= t("user.sort.pending") %>
  <% end %>

  <%= hidden_field_tag :sort, sort_attr %>
  <%= hidden_field_tag :direction, sort_direction %>

  <div class="clearfix"></div>

  <table id="users" class="table table-hover">
    <thead>
      <tr>
        <% %w{ email created_at }.each do |field| %>
          <th>
            <%= link_to admin_users_path(page: params[:page], per: params[:per_page],
                                         sort_attr: field, sort_direction: (sort_attr == field) ? invert_sort_direction : sort_direction,
                                         search: params[:search], pending: params[:pending]), class: "submit" do %>
              <%= t("user.sort.#{field}") %>

              <% if sort_attr == field %>
                &nbsp;
                <%= fa_icon( (sort_direction == "asc") ? "angle-down" : "angle-up" ) %>
              <% end %>
            <% end %>
          </th>
        <% end %>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <%= render @users %>
    </tbody>
  </table>

  <%= paginate @users, remote: true %>
</div>

app/views/admin/users/index.html.erb
<div class="col-sm-7">
  <%= form_tag admin_users_path, id: "admin-users-filter" do %>
    <div class="form-group"></div>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], id: "email-search", class: "form-control",
                         placeholder: t("user.search") %>
    </div>

    <div class="clearfix"></div>

    <%= render "user_list" %>
  <% end %>
</div>

<div class="col-sm-5 scrolltofixed">
  <div id="user-details">
    <div class="alert alert-info"><%= t(".show_details") %></div>
  </div>
</div>