config/routes.rb
Curio::Application.routes.draw do
  mount S3Multipart::Engine => "/s3_multipart"

  devise_for :users, controllers: { registrations: "registrations", confirmations: "confirmations",
                                    sessions: "sessions" }

  devise_scope :user do
    match '/user/confirmation' => 'confirmations#update', via: :put, as: :update_user_confirmation
  end

  get 'thankyou' => 'landing_page#thankyou'

  resources :enrolments, only: :index do
    post :progress, on: :member
  end

  resources :authored_courses, only: :index
  resources :gaming_events, only: [:create, :update, :destroy] do
    post :discover, on: :member
  end

  resources :courses do
    resources :course_chapters do
      get :gamify, on: :member
    end

    member do
      post :reorder
      post :enrol
      get :watch
    end

    collection do
      get :search
      post :search
    end
  end

  resources :course_chapters, only: :create # stub

  resources :users, only: [:index, :show] do
    put :avatar, on: :collection
    resources :score_activities, only: :index
  end

  resources :tutors, only: [:index, :show]
  resources :essays

  namespace :admin do
    root to: "users#index"

    resources :courses, only: [:index, :edit, :destroy]

    resources :users do
      put :approve, on: :member
    end
  end

  get 'tags' => 'tags#index', as: 'tags'

  authenticated :user, ->(u) { u.has_role?(:creative) } do
    root to: "authored_courses#index", as: :tutor_root
  end

  authenticated :user, ->(u) { u.has_role?(:student) } do
    root to: "enrolments#index", as: :student_root
  end

  root to: "landing_page#index"

end

app/views/layouts/_messages.html.erb
<% classes = { notice: "alert alert-success", error: "alert alert-danger", warning: "alert alert-warning", alert: "alert alert-warning" } %>

<div id="flash">
  <% flash.each do |name, msg| %>
    <div class="<%= classes[name] %> alert-dismissable">
      <a class="close" data-dismiss="alert"><%= fa_icon "times" %></a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar-header">
  <%= link_to t("navigation.home"), root_path, class: "navbar-brand" %>

  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
    <span class="sr-only"><%= t("navigation.toggle") %></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
</div>

<div id="navbar-collapse-1" class="collapse navbar-collapse">
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <% if current_user.has_role?(:admin) %>
        <li>
          <%= link_to t('navigation.admin_panel'), admin_root_path %>
        </li>
      <% end %>
      <li id="user-info" class="dropdown">
        <a id="profile" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
          <%= image_tag current_user.avatar.small %>
          <%= current_user.email %><b class="caret"></b>
        </a>
        <ul class="dropdown-menu pull-right" aria-labelledby="profile" role="menu">
          <li><%= link_to t('navigation.my_account'), edit_user_registration_path %></li>
          <li class="divider"></li>
          <li><%= link_to t("navigation.courses"), courses_path %></li>
          <li><%= link_to t("navigation.tutors"), tutors_path %></li>
          <li class="divider"></li>
          <li><%= link_to t('navigation.logout'), destroy_user_session_path, method: 'delete' %></li>
        </ul>
      </li>
    <% else %>
      <li>
        <%= link_to(t('navigation.sign_in'), new_user_session_path) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "picct.me" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700|Poly:400,400italic|Lily+Script+One' rel='stylesheet' type='text/css'>
    <%= yield :head_before %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= i18n_js %>
    <%= yield :head_after %>
  </head>

  <body>
    <nav class="navbar navbar-default" role="navigation">
      <%= render 'layouts/navigation' %>
    </nav>

    <div id="main" role="main">
      <%= yield :admin_nav %>

      <div class="container">
        <div class="row">
          <%= render 'layouts/messages' %>

          <div id="content-wrapper" class="col-md-12">
            <%= yield :home if user_signed_in? %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div> <!--! end of #main -->

    <footer>
    </footer>

  </body>
</html>

app/views/layouts/home.html.erb
<% content_for :home do %>
  <div class="row-fluid">
    <div class="center-block">
      <div id="profile-card" class="clearfix">
        <div class="pull-left">
          <%= image_tag current_user.avatar, alt: current_user.display_name %>
          <h3 class="text-center text-muted"><%= current_user.score %></h3>
        </div>

        <div>
          <h3><%= current_user.display_name %></h3>

          <% if current_user.bio.present? %>
            <p><%= current_user.bio %></p>
          <% else %>
            <p class="text-muted"><%= t(".empty_bio") %></p>
          <% end %>

          <%= link_to t(".edit_profile"), edit_user_registration_path, class: "btn btn-default" %>
        </div>

      </div>
    </div>
  </div>
  <div class="top-2"></div>

  <div class="center-block">
    <div class="text-center">
      <% if can?(:create, Course) %>
        <%= link_to t(".create_course"), new_course_path, class: "btn btn-primary btn-lg" %>
      <% end %>

      <% if can?(:create, Essay) %>
        <%= link_to t(".create_essay"), new_essay_path(author_id: current_user.id), class: "btn btn-primary btn-lg" %>
      <% end %>
    </div>
  </div>

  <div class="row-fluid">
    <ul class="nav nav-tabs">
      <li class="<%= "active" if params[:controller] == "enrolments" %>">
        <%= link_to t(".enrolments"), enrolments_path %>
      </li>

      <% if can?(:create, Course) %>
        <li class="<%= "active" if params[:controller] == "authored_courses" %>">
          <%= link_to t(".authored"), authored_courses_path %>
        </li>
      <% end %>

      <li class="<%= "active" if params[:controller] == "score_activities" %>">
        <%= link_to t(".score"), user_score_activities_path(user_id: current_user.id) %>
      </li>
    </ul>
  </div>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/landing_page.html.erb
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://ogp.me/ns/fb#">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= yield :fb_og_tags %>
    <title>picct.me</title>
    <link href='http://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= i18n_js %>
  </head>

  <body class="landing-page">
    <div class="container">
      <div class="row">
        <%= render 'layouts/messages' %>
      </div>
    </div>

    <div id="landing-page-content" class="col-md-10">
      <div id="logo"></div>

      <%= yield %>
    </div>
  </body>
</html>